### ISSUE TITLE
error in line 16, in <module> import api_keys

### ISSUE THREAD

**Issue by Visalyputra** [joda32/CertCrunchy#2]
This error suddenly appears upon running the code. 
but i have a censys uid key with secret key applied and other api key in the api_keys.py file. 

Traceback (most recent call last):
  File "./certcrunchy.py", line 16, in <module>
    import api_keys
  File "/home/shin/Documents/For Research/CertCrunchy/api_keys.py", line 1
    _censys_uid =

How to fix this error?

**Comment by joda32** [comment]
HI,
By default no API is in the config file and look like this.

_censys_uid = None

when you add an API key you need place your key between double qoutes, for example

_censys_uid = "asdfasdfasdf"

I suspect that is the issue. Please check and let me know, if that is the issue then I think I should update the documentation to explain that better, sorry about that :)

**Comment by Visalyputra** [comment]
yes the issue on the first problem is the " " and it already runs the code. Its ok 

But. a error appear again 
and i already implement the " " and this error still appears.
this is the error message appears.

Traceback (most recent call last):
  File "./certcrunchy.py", line 435, in <module>
    if api_keys._censys_uid and api_keys._censys_secret:
AttributeError: module 'api_keys' has no attribute '_censys_uid'

**Comment by joda32** [comment]
Hi,

Yes I see that I did introduce a bug in a previous commit. I believe it is fixed now, please update from git and test again.

Please let me know and let me know :)

**Comment by Visalyputra** [comment]
Yes. its already been fix. thank you for fixing the bug :)
